I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 246, in script
    $ addPonto(0.5)
  File "game/script.rpy", line 246, in <module>
    $ addPonto(0.5)
NameError: name 'addPonto' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 246, in script
    $ addPonto(0.5)
  File "C:\Users\USUARIO\Downloads\renpy-8.3.3.24100702+nightly-sdk\renpy-8.3.3.24100702+nightly-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\USUARIO\Downloads\renpy-8.3.3.24100702+nightly-sdk\renpy-8.3.3.24100702+nightly-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 246, in <module>
    $ addPonto(0.5)
NameError: name 'addPonto' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.3.24100702+nightly
 
Tue Oct 29 02:00:59 2024
