I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 228, in script
    $ addPonto(0.5)
  File "game/script.rpy", line 228, in <module>
    $ addPonto(0.5)
NameError: name 'addPonto' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 228, in script
    $ addPonto(0.5)
  File "C:\Users\jeanc\OneDrive\Área de Trabalho\renpy-8.3.2-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\jeanc\OneDrive\Área de Trabalho\renpy-8.3.2-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 228, in <module>
    $ addPonto(0.5)
NameError: name 'addPonto' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.2.24090902
Guardian Of the Earth 1.0
Sat Oct 26 11:50:57 2024
